steps:
- id: 'build web'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', 'web', '--config', 'cloudbuild.yaml']
  waitFor: ['-']
- id: 'build api'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', 'api', '--config', 'cloudbuild.yaml']
  waitFor: ['-']