steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'api/Dockerfile', '-t', 'gcr.io/tea-shelf/api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tea-shelf/api']
