version: '3.7'

services:
  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=tea
      - POSTGRES_PASSWORD=tea
      - POSTGRES_DB=tea_dev

  api:
    container_name: api
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - media:/usr/src/app/media
      - static:/usr/src/app/static
    command: gunicorn tea_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - ./api/.env.dev
    depends_on:
      - db

  web:
    container_name: web
    build: ./web
    command: npm start
    ports:
      - 3001:3000
    depends_on:
      - api
    stdin_open: true
    volumes:
      - ./web:/usr/src/app

  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - api
      - web
    ports:
      - 8080:80
    restart: always
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static

volumes:
  postgres_data:
  media:
  static:
