FROM nginx:1.17.6-alpine

RUN apk add python3 python3-dev build-base libressl-dev musl-dev libffi-dev

RUN pip3 install pip --upgrade
RUN pip3 install certbot-nginx
RUN mkdir /etc/letsencrypt
COPY /ssl-renew /etc/periodic/weekly/

RUN apk add --no-cache py-cryptography

RUN rm /etc/nginx/conf.d/default.conf
COPY /include.storage /etc/nginx/app/include.storage
COPY /include.forwarded /etc/nginx/app/include.forwarded
COPY /prod.conf /etc/nginx/conf.d



