FROM nginx:1.17.6-alpine

RUN apk update \
    && apk add python3 python3-dev build-base libressl-dev musl-dev libffi-dev
RUN apk add --no-cache py-cryptography

RUN pip3 install pip --upgrade
RUN pip3 install certbot-nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY /prod.conf /etc/nginx/conf.d

RUN mkdir /etc/letsencrypt
COPY /ssl-renew /etc/periodic/weekly/