steps:
- name: node
  entrypoint: npm
  args: ['install']
#- name: node
#  entrypoint: npm
#  args: ['run', 'build']
#- name: 'gcr.io/cloud-builders/gsutil'
#  args: ['-h', 'Cache-Control:no-cache,max-age=0', '-m', 'cp', '-r', 'build/*', 'gs://teashelf.app/']
- name: node
  entrypoint: npm
  args: ['run', 'docs']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-h', 'Cache-Control:no-cache,max-age=0', '-m', 'cp', '-r', 'docs/*', 'gs://tea-shelf-281917-static/docs/web/']